name: Container

on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:16-buster-slim
      #options: --cpus 2 # For custom container resource
    steps:
      - name: Log node version
        run: | 
          node -v
          cat /etc/os-release