name: Container

on: [push]

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster-slim
    steps:
      - name: Log node version
        run: | 
          node -v
      - name: Step with docker
        uses: docker://node:14-alpine3.15
        with:           # Options
          entrypoint: /bin/echo 
          args: 'Hello World!'

  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:16-buster-slim
      #options: --cpus 2 # For custom container resource
    steps:
      - name: Log node version
        run: | 
          node -v
          cat /etc/os-release